FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# Correction ici : Exécute la commande via /bin/sh -c pour une meilleure compatibilité
CMD ["/bin/sh", "-c", "npm run dev -- --host 0.0.0.0"]
